# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UguYSt7CkUwrULMWZz_mREHzcAiTT_D1

##Aplikasi sedrhana untuk latihan sertifikasi AWS CCP
"""

import streamlit as st
import openai
import os

st.set_page_config(page_title="Chatbot Awams", page_icon="🤖")
st.title("Chatbot Awams")

# Ambil OpenAI key dari Streamlit Secrets / environment variable
openai_api_key = os.getenv("OPENAI_API_KEY")
if openai_api_key:
    openai.api_key = openai_api_key

# Fallback rule-based jawaban sederhana
rule_based_answers = {
    "what is aws": "AWS (Amazon Web Services) is a cloud platform providing computing power, storage, and other services.",
    "what is ec2": "EC2 is Elastic Compute Cloud, a virtual server in AWS.",
    "what is s3": "S3 is Simple Storage Service, used for object storage in AWS.",
}

# Chat history
if "history" not in st.session_state:
    st.session_state.history = []

# Input dari user
user_input = st.text_input("Ask a question about AWS CCP (type your question and hit Enter):")

if user_input:
    st.session_state.history.append({"role": "user", "content": user_input})

    if openai_api_key:
        # Prompt untuk AI generative
        prompt = f"""
        You are a tutor for AWS Certified Cloud Practitioner (CLF-C02).
        Answer the following practice question as if for a quiz:
        - Provide the correct option (A/B/C/D)
        - Explain why the answer is correct, briefly
        Question: {user_input}
        """
        try:
            response = openai.ChatCompletion.create(
                model="gpt-3.5-turbo",
                messages=[{"role": "system", "content": "You are a helpful AWS CCP tutor."},
                          {"role": "user", "content": prompt}]
            )
            ai_reply = response.choices[0].message.content.strip()
        except Exception as e:
            ai_reply = f"Error contacting OpenAI API: {e}"
    else:
        # Fallback jika API key tidak ada
        ai_reply = rule_based_answers.get(user_input.lower(),
                                          "Sorry, I don't know the answer. Try another question.")

    st.session_state.history.append({"role": "assistant", "content": ai_reply})

# Display chat
for chat in st.session_state.history:
    if chat["role"] == "user":
        st.markdown(f"**You:** {chat['content']}")
    else:
        st.markdown(f"**Bot:** {chat['content']}")
